version: "3"
services:
  mykindlenews:
    container_name: mykindlenews 
    build: .
    restart: always
    environment:
      - TZ=America/Chicago
#    network_mode: host
    ports:
      - '8090:8090'
    volumes:
      - ./server/:/server
      - ./config/:/config
      - ./src/:/src
  
